### PR TITLE
LEARN-86 - Use refresh

### PR DESCRIPTION
**Pull request by dmeybohm**
Improve build times with `?refresh` parameter instead of polling, which is particular to Elasticsearch 5.x.

Also change the documentation to default to 5.6+. I will add a branch for 1.x/2.x support and do a release branch as 2.0 after merging this PR.

### CODE REVIEW

**Review by kylerberry — DISMISSED** [review]
seems good but I think @cjsaylor should take a look as well

**Comment by cjsaylor** [comment]
LGTM

**Review by cjsaylor — APPROVED** [review]

**Comment by cjsaylor** [comment]
@dmeybohm @kylerberry The travis builds didn't run though, keep that in mind.

**Review by cjsaylor — CHANGES_REQUESTED** [review]
https://travis-ci.org/zumba/elasticsearchunit/builds/465168039

This should be fixed before merging.

**Comment by cjsaylor** [comment]
@dmeybohm As a tip, if you are going to support 5.6, you should probably run the composer commands from a php5.6 runtime, otherwise it may bring in some libraries that are not compatible with 5.6.

**Comment by dmeybohm** [comment]
@cjsaylor Thanks. Fixed.

**Review by cjsaylor — APPROVED** [review]

**Pull request merged**
